language: python
python:
    - "3.6"

cache:
    pip: true

install:
    - pip install -r requirements.txt
    - pip install codecov

jobs:
    include:
        - stage: test
          script:
              - echo "python version $(python --version) running"
              - echo "pip version $(pip --version) running"
              - make check coverage

#after_success:
#  - codecov -t CODE_COV_TOKEN_HERE