[tool.towncrier]
    package="FILL_ME_IN"
    filename="CHANGELOG.md"
    issue_format = "`#{issue} <https://github.com/FILL_ME_IN/issues/{issue}>`_"

    [[tool.towncrier.type]]
        directory = "breaking"
        name = "Backward-incompatible Changes"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "bugfix"
        name = "Bugfixes"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "deprecation"
        name = "Deprecations"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "feature"
        name = "New Features"
        showcontent = true

[tool.black]
line-length = 90
